import { describe, expect, test } from "bun:test";
import { composeThemeCss } from "./build-theme";

describe("composeThemeCss", () => {
  test("composeThemeCss puts the banner first, then obsidian, then parchment", () => {
    const css = composeThemeCss("1.2.3", ".obsidian { a: 1; }", ".parchment { b: 2; }");
    const lines = css.split("\n");
    expect(lines[0]).toBe(
      '/* GENERATED by ops/admin/theme/build-theme.ts from @rackbops/styles@1.2.3 (arcane-obsidian + arcane-parchment). Do not hand-edit: bump the pin in ops/admin/theme/package.json and run "bun run build" there. */',
    );
    expect(lines.slice(1)).toEqual([".obsidian { a: 1; }", ".parchment { b: 2; }", ""]);
    expect(css.indexOf(".obsidian")).toBeLessThan(css.indexOf(".parchment"));
  });

  test("normalises CRLF to LF", () => {
    const css = composeThemeCss("1.2.3", "a {\r\n  x: 1;\r\n}\r\n\r\n", "b {\r\n  y: 2;\r\n}\r\n");
    expect(css).not.toContain("\r");
    // One trailing newline, however many the bundles ended with.
    expect(css.endsWith("}\n")).toBe(true);
    expect(css.endsWith("\n\n")).toBe(false);
    expect(css.split("\n").slice(1)).toEqual(["a {", "  x: 1;", "}", "b {", "  y: 2;", "}", ""]);
  });
});
