// Build-only: writes ../public/rb-theme.css from the pinned @rackbops/styles. Nothing here runs at
// deploy or at runtime -- the output is committed, the admin image only ever copies it. See
// README.md for the bump procedure.
import { readFileSync, writeFileSync } from "node:fs";

/** A pin must be an exact `x.y.z` -- a range would let a fresh install build different CSS. */
export const EXACT_VERSION_RE = /^\d+\.\d+\.\d+$/;

/** Pure: the full text of rb-theme.css. Line 1 is the banner naming the version it came from (which
 * `ops/admin/server.test.ts` compares against the pin), then the dark (obsidian) bundle, then the
 * light (parchment) bundle -- LF line endings and exactly one trailing newline whatever the
 * bundles' own line endings and trailing blanks were. */
export function composeThemeCss(version: string, obsidian: string, parchment: string): string {
  const banner =
    `/* GENERATED by ops/admin/theme/build-theme.ts from @rackbops/styles@${version} ` +
    `(arcane-obsidian + arcane-parchment). Do not hand-edit: bump the pin in ` +
    `ops/admin/theme/package.json and run "bun run build" there. */`;
  const clean = (css: string) => css.replace(/\r\n?/g, "\n").replace(/\n+$/, "");
  return `${banner}\n${clean(obsidian)}\n${clean(parchment)}\n`;
}

// Everything below only runs as the entry point (`bun run build-theme.ts`), never on import, so the
// test file can import composeThemeCss with no side effects.
if (import.meta.main) {
  const fail = (message: string): never => {
    console.error(`build-theme: ${message}`);
    process.exit(1);
  };
  const readText = (relative: string): string => {
    try {
      return readFileSync(new URL(relative, import.meta.url), "utf8");
    } catch (err) {
      return fail(`couldn't read ${relative} (${err instanceof Error ? err.message : err}) -- did you run "bun install" here?`);
    }
  };

  const pin: unknown = JSON.parse(readText("./package.json")).devDependencies?.["@rackbops/styles"];
  if (typeof pin !== "string" || !EXACT_VERSION_RE.test(pin)) {
    fail(`the @rackbops/styles pin in package.json must be an exact x.y.z version, got ${JSON.stringify(pin)}`);
  }
  const version = pin as string;
  const installed: unknown = JSON.parse(readText("./node_modules/@rackbops/styles/package.json")).version;
  if (installed !== version) {
    fail(`installed @rackbops/styles is ${String(installed)} but package.json pins ${version} -- run "bun install"`);
  }

  const css = composeThemeCss(
    version,
    readText("./node_modules/@rackbops/styles/arcane-obsidian/bundle.css"),
    readText("./node_modules/@rackbops/styles/arcane-parchment/bundle.css"),
  );
  writeFileSync(new URL("../public/rb-theme.css", import.meta.url), css);
  console.log(`build-theme: wrote public/rb-theme.css from @rackbops/styles@${version} (${css.length} bytes)`);
}
