// The host<->plugin contract — types plus one integer constant, nothing else. This module must stay
// free of runtime imports and side effects: the Plugin Index (the JSON these types describe) is read
// at boot BEFORE the discord.js Client exists (intents are frozen at construction, so they have to
// come from data, never from plugin code), and the plugins repo vendors this file verbatim to
// type-check plugins against it. Design: docs/adr/0004-plugins-fetched-from-a-published-manifest.md.
import type {
  AutocompleteInteraction,
  ChatInputCommandInteraction,
  MessageComponentInteraction,
  ModalSubmitInteraction,
  RESTPostAPIChatInputApplicationCommandsJSONBody,
  SlashCommandBuilder,
} from "discord.js";

/**
 * Bumped when `HostApi`/`Plugin` change incompatibly. A Plugin Index entry declaring a different
 * value is skipped with a reason: its current version is never installed or loaded. That does not
 * always mean the plugin as a whole is never loaded (#222): when the entry needs a NEWER host than
 * this one, an older version pinned in `PLUGINS` or recorded in the previous boot's `state.json` is
 * kept running instead, provided the entry declares no intents — the exact conditions are in
 * `selectPlugins`, `src/plugins/registry.ts`. Integer equality on purpose — every plugin is built
 * against one exact host API — a range can come later if plugins ever outlive host versions.
 */
export const HOST_API_VERSION = 1;

// ---------------------------------------------------------------------------------------------------
// The published manifest (plugins.json): bot-agnostic, generated by the plugins repo's CI from each
// plugin's package.json "botPlugin" block and CHANGELOG.md, never hand-edited.
// ---------------------------------------------------------------------------------------------------

/**
 * One env key a plugin owns. `format` is a POSIX ERE in bash's `[[ =~ ]]` dialect (keep to the common
 * subset — it may be evaluated in a C locale, so enumerate characters, never multibyte ranges); it is
 * consumed by `ops/bot-ops.sh env-set` to validate a changed value, never by the bot itself (the
 * plugin parses its own config from `HostApi.env`). `required` mirrors bot-ops.sh's `REQUIRED` set
 * (env-set refuses to blank it). `secret` keys are never listed or edited by ops tooling, exactly like
 * the core secrets (`DISCORD_TOKEN`, `GITHUB_TOKEN`, …).
 */
export interface PluginEnvKey {
  key: string;
  format: string;
  required?: boolean;
  secret?: boolean;
  description: string;
}

/**
 * One named place a plugin can post (#219), declared in its manifest so the operator can map it to a
 * channel per server in the admin panel. `name` is `^[a-z][a-z0-9-]*$` — what the plugin passes as
 * `HostApi.announce`'s `destination`; `description` is what the panel shows beside the picker.
 */
export interface PluginDestination {
  name: string;
  description: string;
}

/** One published version, extracted from the plugin's CHANGELOG.md — what the update notification shows. */
export interface PluginRelease {
  version: string;
  publishedAt: string; // ISO-8601
  url: string; // the GitHub release for this version
  notes: string; // markdown, the CHANGELOG section for this version
}

export interface PluginIndexEntry {
  /** `^[a-z][a-z0-9-]*$` — the `PLUGINS=` token, the log prefix `[name]`, and the `data/plugins/<name>` directory. */
  name: string;
  /** npm package name, e.g. `@rackbops/plugin-warbandeer`; the host resolves `package@version` on the registry. */
  package: string;
  /** Current version (semver). The host never installs it unasked once a version is pinned — see ADR-0004. */
  version: string;
  description: string;
  /** Must equal `HOST_API_VERSION` to be installable; a newer plugin that needs a newer host is reported, not installed. */
  hostApiVersion: number;
  /** `GatewayIntentBits` values as numbers, so the JSON needs no discord.js; unioned into the Client before construction.
   *  RESERVED for a future event seam: declaring one gives the plugin NO gateway events today. The host owns every
   *  gateway listener and passes a plugin only the interactions addressed to it (its slash commands, and component/modal
   *  interactions whose `customId` starts with `<name>:`), whatever intents it declares. What a declared intent does do
   *  is widen the gateway subscription of the WHOLE bot (it joins the one shared Client), privileged intents included,
   *  and a privileged one the operator has not enabled is a login failure (see `selectPlugins`, `src/plugins/registry.ts`).
   *  Declare none. */
  intents?: number[];
  /** Bare slash-command names the bundle contributes; uniqueness (core + every enabled plugin) is checked BEFORE any code loads. */
  commands: string[];
  env: PluginEnvKey[];
  /** Named places this plugin can post besides its main one (#219) — see `HostApi.announce`. Absent = none. */
  destinations?: PluginDestination[];
  /** jsDelivr-npm URL of the plugin's admin bundle (`dist/admin.js`), DERIVED by the plugins repo's
   *  `generate-index` when a plugin advertises admin support (by declaring `botPlugin.adminApiVersion`).
   *  Absent = the plugin contributes no admin UI. The admin panel fetches it and serves it same-origin
   *  under its own tab; see the admin contract (a SEPARATE module from this file). */
  adminUrl?: string;
  /** The `ADMIN_API_VERSION` the plugin's admin bundle was built against; the panel mounts the bundle
   *  only when this equals the panel's own `ADMIN_API_VERSION`, else it shows a version-mismatch note.
   *  Absent = no admin bundle. The admin contract (`AdminApi`/`mountAdmin`/`ADMIN_API_VERSION`) lives
   *  in its own module (browser/DOM-typed) so this file can stay the single-const, side-effect-free
   *  module read at boot before the Client exists. */
  adminApiVersion?: number;
  /** Latest first, at most 10. */
  releases: PluginRelease[];
}

export interface PluginIndex {
  schemaVersion: 1;
  generatedAt: string; // ISO-8601
  plugins: PluginIndexEntry[];
}

// ---------------------------------------------------------------------------------------------------
// What the bot writes under data/plugins/ — read by ops/bot-ops.sh status and the admin panel.
// ---------------------------------------------------------------------------------------------------

export interface PluginStateEntry {
  name: string;
  /** Listed in `PLUGINS=`. */
  enabled: boolean;
  /** The pinned version — what a restart reinstalls, and the last version that actually came up
   *  (kept honest for the panel / `ops/bot-ops.sh status`). Absent when never installed. */
  installedVersion?: string;
  /** #104: a transient "trying to become this" set by `/plugins update` (now or scheduled). The next
   *  boot's install prefers it over `installedVersion`; `buildPluginStateFile` then CONSUMES it — on
   *  success `installedVersion` becomes it and this clears; on failure it clears and `installedVersion`
   *  stays the last-good, so a broken target reverts instead of pinning itself forever. */
  targetVersion?: string;
  /** The index's current version, present only when it is newer than `installedVersion`. */
  availableVersion?: string;
  /** Every env key the plugin expects is present. Enabled-but-unconfigured plugins still load. */
  configured: boolean;
  missingEnv: string[];
  /** Loaded and `activate()` succeeded this boot. */
  active: boolean;
  /** Why it is not active (unknown name, incompatible host API, download/integrity failure, a throw). */
  error?: string;
  /** Last version the admins were notified about. */
  notifiedVersion?: string;
  /** "Skip this version" — no notification until a newer version appears. */
  skippedVersion?: string;
  /** ISO-8601 time a snoozed notification fires again. */
  remindAt?: string;
  /** A scheduled update, executed by the bot at `at` with a heads-up to `requestedBy`. */
  scheduled?: { version: string; at: string; requestedBy: string };
}

/** The follow-up owed after an update restart: who asked, and for what. Consumed once on boot. */
export interface PluginPendingReport {
  plugin: string;
  toVersion: string;
  userId: string;
  channelId?: string;
  requestedAt: number; // ms epoch
}

export interface PluginStateFile {
  hostApiVersion: number;
  writtenAt: string; // ISO-8601
  plugins: PluginStateEntry[];
  /** A single slot — normally enough, since one restart carries one owed report. If two update
   *  actions fire in the same brief pre-restart window, the second's report overwrites the first's:
   *  a lost *confirmation DM* only, never a wrong or lost update (each plugin's pin is consumed
   *  independently, and the report reads the surviving plugin's own state). Acceptable for v1. */
  pendingReport?: PluginPendingReport;
}

/**
 * A request the admin panel drops into `data/plugins/requests/` (via `ops/bot-ops.sh plugin-request`);
 * the bot consumes them on its scheduler tick. The bot stays the only writer of `state.json`.
 */
export type PluginRequest =
  | { action: "update-now"; plugin: string; version: string; requestedBy: string }
  | { action: "schedule"; plugin: string; version: string; at: string; requestedBy: string }
  | { action: "remind"; plugin: string; version: string; days?: number; requestedBy: string }
  | { action: "skip"; plugin: string; version: string; requestedBy: string }
  | { action: "cancel"; plugin: string; requestedBy: string };

// ---------------------------------------------------------------------------------------------------
// The in-process contract between the host and a loaded bundle.
// ---------------------------------------------------------------------------------------------------

/** `console.*` with a `[name] ` prefix, so a plugin's lines read like the bot's own. */
export interface PluginLog {
  info(message: string): void;
  warn(message: string): void;
  error(message: string, err?: unknown): void;
}

/**
 * `src/storage.ts`'s primitives (`src/warbandeer/storage.ts` until it moves), handed over so a bundle
 * needs no copy of them: atomic temp-file-then-rename writes, corrupt-file-moved-aside reads, and the
 * two serializing wrappers (`createJsonWriter` for one whole-value file, `createKeyedJsonMutator`
 * when a read-modify-write per path must be ordered too).
 */
export interface HostStorage {
  readJsonOrFresh<T>(path: string, fresh: () => T, label: string): Promise<T>;
  writeJsonAtomic(path: string, data: unknown): Promise<void>;
  createJsonWriter<T>(path: string): { save: (data: T) => Promise<void> };
  createKeyedJsonMutator<T>(): {
    update: (path: string, fresh: () => T, mutate: (current: T) => T, label: string) => Promise<void>;
  };
}

/**
 * Everything a plugin may touch. Deliberately no discord.js `Client`: the host owns every gateway
 * listener (nothing plugin-side may attach before `takeOver()` completes during a self-update
 * handoff), and a fake host is all a plugin's tests need. A declared-dependency boundary, not a
 * sandbox: a command handler's `interaction.client` still reaches the live `Client`.
 */
export interface HostApi {
  readonly name: string;
  /** ONLY the keys declared in this plugin's Plugin Index entry — never the whole environment. */
  readonly env: Readonly<Record<string, string | undefined>>;
  /** The one `data/` directory (`/app/data` in the image); plugin-owned files live directly under it. */
  readonly dataDir: string;
  readonly log: PluginLog;
  readonly storage: HostStorage;
  /** Posts `message` wherever the operator has routed this plugin's announcements (ADR-0006, `src/routing/post.ts`): every
   *  channel its routing names, or `ANNOUNCE_CHANNEL_ID` when it names none — the plugin does not choose. Each channel is
   *  posted through its registered webhook when it has a working one, and as the bot otherwise (a webhook that times out may
   *  already have delivered, so the fallback can put a second copy there); mention-safe defaults apply on both paths.
   *  Rejects only when EVERY target failed, with the first error, so a plugin that retries after a rejection does not
   *  repost to the channels that did get the message.
   *
   *  `destination` (#219) names one of the `destinations` the plugin's manifest declares — a second kind of post that
   *  wants its own channel. The operator maps each name to a channel per server in the panel; the message goes to every
   *  channel mapped for that name. Where the name is mapped nowhere, it posts exactly as it would without one, so a
   *  destination is an option the operator can take up, never something that stops a post. A name the manifest does not
   *  declare is logged and treated the same way. */
  announce(message: string, destination?: string): Promise<void>;
}

export interface PluginCommand {
  /** Bare name. The host hands `build` an ALREADY-NAMED builder (`COMMAND_PREFIX` applied), so a plugin cannot register outside the namespace. */
  name: string;
  build(builder: SlashCommandBuilder): { toJSON(): RESTPostAPIChatInputApplicationCommandsJSONBody };
  handle(interaction: ChatInputCommandInteraction): Promise<void>;
  /**
   * Answers Discord's picker for an option this command built with `setAutocomplete(true)` (#287). The
   * plugin reads the option being typed (`interaction.options.getFocused(true)`) and answers with
   * `await interaction.respond(choices)` — at most 25, within Discord's 3 s (the host stops waiting at
   * 2.5 s). It runs only where the command itself may run (the same routing gate as `handle`, failing
   * closed here) and only while the plugin is running. Where it is absent, throws, or returns without
   * calling `respond`, the host answers with an empty list, so the picker closes cleanly; a `respond`
   * that Discord rejects (e.g. after its 3 s) is the plugin's own failure. Optional: a command with no
   * autocomplete option omits it.
   */
  autocomplete?(interaction: AutocompleteInteraction): Promise<void>;
}

/**
 * One scheduler check, run inside the bot's guarded tick with the core checks; failures are isolated per check.
 *
 * What the host does with a plugin's tick (#217, #248, `pluginTicks` in `src/plugins/host.ts`):
 * - Each call is waited on for at most `PLUGIN_TICK_TIMEOUT_MS` (currently 30 s). Past that the host stops WAITING
 *   and logs the overrun as this plugin's failure; it aborts the call's signal (below), but a call that ignores the
 *   signal keeps running.
 * - A tick is skipped, with a warning, while its own previous call is still pending, so it never runs concurrently
 *   with itself. That guard is per tick, not per plugin: the plugin's OTHER ticks keep running, concurrently with
 *   the abandoned call.
 * - A call that is merely slow recovers once it settles; one that never settles silences that one tick until the
 *   bot restarts.
 * - `run` is passed an `AbortSignal` (#248). The host aborts it at the timeout, and when the bot is asked to stop (a
 *   restart, or a SIGTERM/SIGINT). A restart or a stop then waits a few seconds (`PLUGIN_TICK_ABORT_GRACE_MS`, 5 s)
 *   for every pending call to settle — including one the timeout abandoned — before it exits; no new call starts
 *   once a stop is under way. A tick that honours the signal (pass it to `fetch`, check `signal.aborted` before a
 *   write or a post, and return) therefore gets to stop at a point of its choosing — but only within the grace: a
 *   step it has already started, such as an `announce` in flight, is not itself cancelled and can still be cut off
 *   once the grace is spent. A tick that ignores the signal keeps working as before, and a stop exits under it once
 *   the grace is spent, so a tick that announces should still write its dedup key BEFORE it announces. An abort
 *   listener must not throw: like a throw from the plugin's own timer, it is reported as an uncaught exception. The parameter is optional to read: a plugin built before it
 *   existed is unaffected.
 */
export interface TickCheck {
  name: string;
  run(signal?: AbortSignal): Promise<void>;
}

/**
 * Called for any component/modal interaction whose `customId` starts with `<name>:` (the plugin's
 * manifest name + colon) — the host strips nothing, the plugin sees the full id. The plugin must
 * reply/defer itself; a throw is logged and isolated (the host sends a best-effort ephemeral error
 * reply on the plugin's behalf only if it hasn't replied/deferred yet).
 */
export type PluginInteractionHandler = (
  interaction: MessageComponentInteraction | ModalSubmitInteraction,
) => Promise<void>;

/**
 * What the host tells a plugin's `http` handler about one request (#220, ADR-0007), besides the
 * `Request` itself.
 */
export interface PluginHttpInfo {
  /** The request path after `/<plugin-name>`: `"/"` for `/<name>` and `/<name>/`, `"/callback"` for
   *  `/<name>/callback`. Still percent-encoded, exactly as it arrived. No query string. */
  path: string;
  /** `CF-Connecting-IP`, falling back to the socket address, or `"unknown"`. Trustworthy only for
   *  what really came through Cloudflare's tunnel (ADR-0007 decision 2). */
  clientIp: string;
}

export interface Plugin {
  commands?: readonly PluginCommand[];
  ticks?: readonly TickCheck[];
  /** Runs once, inside the bot's `activate()`, after `takeOver()`. All side effects (files, servers) belong here. */
  activate?(): Promise<void>;
  /**
   * `activate()`'s counterpart (#184) — runs once, on the way out: a `docker stop`, a self-update's
   * retire, `SIGINT`. Release whatever `activate()` acquired here (servers, handles, timers). Must
   * not throw — the host isolates a throw and continues disposing the rest — and is bounded by the
   * host's own shutdown grace, so a slow or wedged `dispose` loses the remainder of its cleanup
   * rather than delaying the process past the daemon's own SIGKILL. Optional: a plugin with nothing
   * to release (no servers, no long-lived handles) can omit it.
   */
  dispose?(): Promise<void>;
  interactions?: PluginInteractionHandler;
  /**
   * Serves HTTP under `/<plugin-name>/` on the bot's own listener (#220, ADR-0007), which runs only
   * when the operator sets `HTTP_PORT`, and is reached from outside only through the instance's
   * tunnel. Called only while the plugin is running, with the prefix already stripped
   * (`info.path`); the untouched `request` carries the full URL, headers, query and body. The host
   * caps a body at 1 MiB (enforce your own tighter limit), answers for you with `504` once you have
   * taken 10 s (without cancelling the call), and with `500` if you throw. A request is not a
   * critical section: a restart does not wait for it, so write through `HostStorage`. Optional: a
   * plugin that serves no HTTP omits it.
   */
  http?(request: Request, info: PluginHttpInfo): Promise<Response>;
}

/**
 * The bundle's export. `createPlugin` must be pure (no I/O) — it may throw to refuse, e.g. on an
 * invalid env value, with the same error text the bot used to throw at boot; the host then skips the
 * plugin and logs the reason instead of refusing to start.
 */
export interface PluginModule {
  createPlugin(host: HostApi): Plugin;
}
