// The host<->plugin contract — types plus one integer constant, nothing else. This module must stay
// free of runtime imports and side effects: the Plugin Index (the JSON these types describe) is read
// at boot BEFORE the discord.js Client exists (intents are frozen at construction, so they have to
// come from data, never from plugin code), and the plugins repo vendors this file verbatim to
// type-check plugins against it. Design: docs/adr/0004-plugins-fetched-from-a-published-manifest.md.
import type {
  ChatInputCommandInteraction,
  RESTPostAPIChatInputApplicationCommandsJSONBody,
  SlashCommandBuilder,
} from "discord.js";

/**
 * Bumped when `HostApi`/`Plugin` change incompatibly. A Plugin Index entry declaring a different
 * value is skipped with a reason and never loaded. Integer equality on purpose — every plugin is
 * built against one exact host API — a range can come later if plugins ever outlive host versions.
 */
export const HOST_API_VERSION = 1;

// ---------------------------------------------------------------------------------------------------
// The published manifest (plugins.json): bot-agnostic, generated by the plugins repo's CI from each
// plugin's package.json "botPlugin" block and CHANGELOG.md, never hand-edited.
// ---------------------------------------------------------------------------------------------------

/**
 * One env key a plugin owns. `format` is a POSIX ERE in bash's `[[ =~ ]]` dialect (keep to the common
 * subset — it may be evaluated in a C locale, so enumerate characters, never multibyte ranges); it is
 * consumed by `ops/bot-ops.sh env-set` to validate a changed value, never by the bot itself (the
 * plugin parses its own config from `HostApi.env`). `required` mirrors bot-ops.sh's `REQUIRED` set
 * (env-set refuses to blank it). `secret` keys are never listed or edited by ops tooling, exactly like
 * the core secrets (`DISCORD_TOKEN`, `GITHUB_TOKEN`, …).
 */
export interface PluginEnvKey {
  key: string;
  format: string;
  required?: boolean;
  secret?: boolean;
  description: string;
}

/** One published version, extracted from the plugin's CHANGELOG.md — what the update notification shows. */
export interface PluginRelease {
  version: string;
  publishedAt: string; // ISO-8601
  url: string; // the GitHub release for this version
  notes: string; // markdown, the CHANGELOG section for this version
}

export interface PluginIndexEntry {
  /** `^[a-z][a-z0-9-]*$` — the `PLUGINS=` token, the log prefix `[name]`, and the `data/plugins/<name>` directory. */
  name: string;
  /** npm package name, e.g. `@rackbops/plugin-warbandeer`; the host resolves `package@version` on the registry. */
  package: string;
  /** Current version (semver). The host never installs it unasked once a version is pinned — see ADR-0004. */
  version: string;
  description: string;
  /** Must equal `HOST_API_VERSION` to be installable; a newer plugin that needs a newer host is reported, not installed. */
  hostApiVersion: number;
  /** `GatewayIntentBits` values as numbers, so the JSON needs no discord.js; unioned into the Client before construction. */
  intents?: number[];
  /** Bare slash-command names the bundle contributes; uniqueness (core + every enabled plugin) is checked BEFORE any code loads. */
  commands: string[];
  env: PluginEnvKey[];
  /** Latest first, at most 10. */
  releases: PluginRelease[];
}

export interface PluginIndex {
  schemaVersion: 1;
  generatedAt: string; // ISO-8601
  plugins: PluginIndexEntry[];
}

// ---------------------------------------------------------------------------------------------------
// What the bot writes under data/plugins/ — read by ops/bot-ops.sh status and the admin panel.
// ---------------------------------------------------------------------------------------------------

export interface PluginStateEntry {
  name: string;
  /** Listed in `PLUGINS=`. */
  enabled: boolean;
  /** The pinned version — what a restart reinstalls. Absent when never installed. */
  installedVersion?: string;
  /** The index's current version, present only when it is newer than `installedVersion`. */
  availableVersion?: string;
  /** Every env key the plugin expects is present. Enabled-but-unconfigured plugins still load. */
  configured: boolean;
  missingEnv: string[];
  /** Loaded and `activate()` succeeded this boot. */
  active: boolean;
  /** Why it is not active (unknown name, incompatible host API, download/integrity failure, a throw). */
  error?: string;
  /** Last version the admins were notified about. */
  notifiedVersion?: string;
  /** "Skip this version" — no notification until a newer version appears. */
  skippedVersion?: string;
  /** ISO-8601 time a snoozed notification fires again. */
  remindAt?: string;
  /** A scheduled update, executed by the bot at `at` with a heads-up to `requestedBy`. */
  scheduled?: { version: string; at: string; requestedBy: string };
}

/** The follow-up owed after an update restart: who asked, and for what. Consumed once on boot. */
export interface PluginPendingReport {
  plugin: string;
  toVersion: string;
  userId: string;
  channelId?: string;
  requestedAt: number; // ms epoch
}

export interface PluginStateFile {
  hostApiVersion: number;
  writtenAt: string; // ISO-8601
  plugins: PluginStateEntry[];
  pendingReport?: PluginPendingReport;
}

/**
 * A request the admin panel drops into `data/plugins/requests/` (via `ops/bot-ops.sh plugin-request`);
 * the bot consumes them on its scheduler tick. The bot stays the only writer of `state.json`.
 */
export type PluginRequest =
  | { action: "update-now"; plugin: string; version: string; requestedBy: string }
  | { action: "schedule"; plugin: string; version: string; at: string; requestedBy: string }
  | { action: "remind"; plugin: string; version: string; days?: number; requestedBy: string }
  | { action: "skip"; plugin: string; version: string; requestedBy: string }
  | { action: "cancel"; plugin: string; requestedBy: string };

// ---------------------------------------------------------------------------------------------------
// The in-process contract between the host and a loaded bundle.
// ---------------------------------------------------------------------------------------------------

/** `console.*` with a `[name] ` prefix, so a plugin's lines read like the bot's own. */
export interface PluginLog {
  info(message: string): void;
  warn(message: string): void;
  error(message: string, err?: unknown): void;
}

/**
 * `src/storage.ts`'s primitives (`src/warbandeer/storage.ts` until it moves), handed over so a bundle
 * needs no copy of them: atomic temp-file-then-rename writes, corrupt-file-moved-aside reads, and the
 * two serializing wrappers (`createJsonWriter` for one whole-value file, `createKeyedJsonMutator`
 * when a read-modify-write per path must be ordered too).
 */
export interface HostStorage {
  readJsonOrFresh<T>(path: string, fresh: () => T, label: string): Promise<T>;
  writeJsonAtomic(path: string, data: unknown): Promise<void>;
  createJsonWriter<T>(path: string): { save: (data: T) => Promise<void> };
  createKeyedJsonMutator<T>(): {
    update: (path: string, fresh: () => T, mutate: (current: T) => T, label: string) => Promise<void>;
  };
}

/**
 * Everything a plugin may touch. Deliberately no discord.js `Client`: the host owns every gateway
 * listener (nothing plugin-side may attach before `takeOver()` completes during a self-update
 * handoff), and a fake host is all a plugin's tests need. A declared-dependency boundary, not a
 * sandbox: a command handler's `interaction.client` still reaches the live `Client`.
 */
export interface HostApi {
  readonly name: string;
  /** ONLY the keys declared in this plugin's Plugin Index entry — never the whole environment. */
  readonly env: Readonly<Record<string, string | undefined>>;
  /** The one `data/` directory (`/app/data` in the image); plugin-owned files live directly under it. */
  readonly dataDir: string;
  readonly log: PluginLog;
  readonly storage: HostStorage;
  /** Posts to `ANNOUNCE_CHANNEL_ID`, through the bot's own send path (mention-safe defaults apply). */
  announce(message: string): Promise<void>;
}

export interface PluginCommand {
  /** Bare name. The host hands `build` an ALREADY-NAMED builder (`COMMAND_PREFIX` applied), so a plugin cannot register outside the namespace. */
  name: string;
  build(builder: SlashCommandBuilder): { toJSON(): RESTPostAPIChatInputApplicationCommandsJSONBody };
  handle(interaction: ChatInputCommandInteraction): Promise<void>;
}

/** One scheduler check, run inside the bot's guarded tick with the core checks; failures are isolated per check. */
export interface TickCheck {
  name: string;
  run(): Promise<void>;
}

export interface Plugin {
  commands?: readonly PluginCommand[];
  ticks?: readonly TickCheck[];
  /** Runs once, inside the bot's `activate()`, after `takeOver()`. All side effects (files, servers) belong here. */
  activate?(): Promise<void>;
}

/**
 * The bundle's export. `createPlugin` must be pure (no I/O) — it may throw to refuse, e.g. on an
 * invalid env value, with the same error text the bot used to throw at boot; the host then skips the
 * plugin and logs the reason instead of refusing to start.
 */
export interface PluginModule {
  createPlugin(host: HostApi): Plugin;
}
